language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - bash ./ci_build.sh
matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
